
import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import API from "../services/api";

import {
  FiArrowLeft,
  FiRefreshCw,
  FiTrendingUp,
  FiTrendingDown,
  FiDollarSign,
  FiPackage,
  FiUsers,
  FiAlertTriangle,
  FiCheckCircle,
  FiTarget,
  FiShoppingCart,
  FiBarChart2,
  FiActivity,
  FiZap,
  FiShield,
  FiCalendar,
  FiClock,
} from "react-icons/fi";

export default function AIBusiness() {
  const navigate = useNavigate();

  const [loading, setLoading] = useState(false);
  const [firstLoading, setFirstLoading] = useState(true);
  const [error, setError] = useState("");
  const [analysis, setAnalysis] = useState(null);

  const businessName =
    localStorage.getItem("businessName") || "Your Business";

  // ============================================================
  // LOAD AI BUSINESS ANALYSIS
  // ============================================================

  const loadAnalysis = async () => {
    try {
      setLoading(true);
      setError("");

      // Business ID is NOT sent from the browser.
      // The backend gets it securely from req.businessId.
      const response = await API.get("/ai-business/strategy");

      if (response.data) {
        setAnalysis(response.data.data || response.data);
      }
    } catch (err) {
      console.error("AI Business Analysis Error:", err);

      setError(
        err.response?.data?.message ||
          "Unable to generate business analysis."
      );
    } finally {
      setLoading(false);
      setFirstLoading(false);
    }
  };

  useEffect(() => {
    loadAnalysis();
  }, []);

  // ============================================================
  // HELPERS
  // ============================================================

  const number = (value) => {
    const n = Number(value);
    return Number.isFinite(n) ? n : 0;
  };

  const money = (value) => {
    return `₹${number(value).toLocaleString("en-IN", {
      maximumFractionDigits: 2,
    })}`;
  };

  const percentage = (value) => {
    return `${number(value).toFixed(1)}%`;
  };

  const getValue = (...values) => {
    for (const value of values) {
      if (
        value !== undefined &&
        value !== null &&
        value !== ""
      ) {
        return value;
      }
    }

    return 0;
  };

  // ============================================================
  // SUPPORT DIFFERENT BACKEND RESPONSE NAMES
  // ============================================================

  const data = analysis || {};

  // Exact structure returned by businessAnalytics.js
  const sales = data.sales || {};
  const inventory = data.inventory || {};
  const customers = data.customers || {};
  const products = data.products || {};
  const suppliers = data.suppliers || {};
  const purchases = data.purchases || {};
  const categories = Array.isArray(data.categories)
    ? data.categories
    : [];
  const payments = Array.isArray(data.payments)
    ? data.payments
    : [];
  const dailySales = Array.isArray(data.daily_sales)
    ? data.daily_sales
    : [];

  // Step 2 AI Strategy Engine response.
  // The strategy endpoint returns the original analytics together
  // with AI-generated health, opportunities, risks and action plans.
  const opportunities = Array.isArray(data.opportunities)
    ? data.opportunities
    : [];

  const risks = Array.isArray(data.risks)
    ? data.risks
    : [];

  const actions = Array.isArray(data.action_plan)
    ? data.action_plan
    : Array.isArray(data.actions)
      ? data.actions
      : [];

  const health = data.health || {};
  const profit = data.profit || {};

  // Strategy sections generated by aiStrategyEngine.js.
  const salesStrategy = data.sales_strategy || {};
  const inventoryStrategy = data.inventory_strategy || {};
  const productStrategy = data.product_strategy || {};
  const customerStrategy = data.customer_strategy || {};
  const purchaseStrategy = data.purchase_strategy || {};
  const categoryStrategy = data.category_strategy || {};
  const paymentStrategy = data.payment_strategy || {};

  // Backward-compatible fallback for older response versions.
  const strategy = data.strategy || {};

  const executiveSummary =
    data.executive_summary || {};

  // ============================================================
  // LOADING SCREEN
  // ============================================================

  if (firstLoading) {
    return (
      <div style={styles.page}>
        <div style={styles.loadingBox}>
          <div style={styles.aiLoadingIcon}>
            <FiZap size={32} />
          </div>

          <h2 style={styles.loadingTitle}>
            AI Business Engine
          </h2>

          <p style={styles.loadingText}>
            Analyzing your business data...
          </p>

          <div style={styles.spinner}></div>
        </div>
      </div>
    );
  }

  // ============================================================
  // PAGE
  // ============================================================

  return (
    <div style={styles.page}>
      {/* ======================================================
          TOP HEADER
      ====================================================== */}

      <div style={styles.header}>
        <div style={styles.headerLeft}>
          <button
            onClick={() => navigate("/dashboard")}
            style={styles.backButton}
          >
            <FiArrowLeft size={18} />
            Dashboard
          </button>

          <div>
            <div style={styles.titleRow}>
              <div style={styles.aiIcon}>
                <FiZap size={25} />
              </div>

              <div>
                <h1 style={styles.title}>
                  AI Business Engine
                </h1>

                <p style={styles.subtitle}>
                  Data-driven strategy, planning and business decisions
                </p>
              </div>
            </div>
          </div>
        </div>

        <button
          onClick={loadAnalysis}
          disabled={loading}
          style={{
            ...styles.analyzeButton,
            opacity: loading ? 0.7 : 1,
          }}
        >
          <FiRefreshCw
            size={17}
            style={{
              animation: loading
                ? "aiSpin 1s linear infinite"
                : "none",
            }}
          />

          {loading
            ? "Analyzing..."
            : "Analyze My Business"}
        </button>
      </div>

      {/* ======================================================
          BUSINESS BANNER
      ====================================================== */}

      <div style={styles.businessBanner}>
        <div>
          <div style={styles.bannerSmall}>
            BUSINESS INTELLIGENCE
          </div>

          <div style={styles.bannerName}>
            {businessName}
          </div>

          <div style={styles.bannerDescription}>
            AI is analyzing your sales, products, inventory, customers and performance to create an action plan.
          </div>
        </div>

        <div style={styles.bannerAI}>
          <FiActivity size={34} />
          <span>AI ACTIVE</span>
        </div>
      </div>

      {/* ======================================================
          AI EXECUTIVE SUMMARY
      ====================================================== */}

      {(executiveSummary.summary ||
        executiveSummary.message ||
        health.score !== undefined ||
        health.status) && (
        <>
          <SectionHeader
            icon={<FiZap />}
            title="AI Executive Summary"
            description="The strategy engine's high-level view of your business"
          />

          <div style={styles.largeCard}>
            <div style={styles.executiveGrid}>
              <div style={styles.executiveSummaryBox}>
                <div style={styles.aiLabel}>AI BUSINESS SUMMARY</div>
                <div style={styles.executiveText}>
                  {executiveSummary.summary ||
                    executiveSummary.message ||
                    "The AI strategy engine has analyzed your business data and prepared prioritized recommendations."}
                </div>
              </div>

              <div style={styles.healthBox}>
                <div style={styles.healthLabel}>BUSINESS HEALTH</div>
                <div style={styles.healthScore}>
                  {health.score !== undefined
                    ? number(health.score).toFixed(0)
                    : "--"}
                </div>
                <div style={styles.healthStatus}>
                  {health.status || "Analyzing"}
                </div>
              </div>
            </div>
          </div>
        </>
      )}

      {/* ======================================================
          ERROR
      ====================================================== */}

      {error && (
        <div style={styles.errorBox}>
          <FiAlertTriangle size={20} />

          <div>
            <strong>AI analysis unavailable</strong>

            <div style={styles.errorText}>
              {error}
            </div>
          </div>

          <button
            onClick={loadAnalysis}
            style={styles.retryButton}
          >
            Retry
          </button>
        </div>
      )}

      {/* ======================================================
          BUSINESS HEALTH
      ====================================================== */}

      <SectionHeader
        icon={<FiActivity />}
        title="Business Health"
        description="Overall performance detected by the AI engine"
      />

      <div style={styles.cardGrid}>
        <MetricCard
          icon={<FiDollarSign />}
          title="Revenue"
          value={money(
            getValue(
              sales.current_month?.revenue,
              sales.today?.revenue,
              0
            )
          )}
          description="Total business revenue"
          type="green"
        />

        <MetricCard
          icon={<FiTrendingUp />}
          title="Sales Growth"
          value={percentage(
            getValue(
              sales.growth?.revenue_percent,
              0
            )
          )}
          description="Business sales growth"
          type="blue"
        />

        <MetricCard
          icon={<FiPackage />}
          title="Inventory"
          value={number(
            getValue(
              inventory.total_stock,
              0
            )
          ).toLocaleString("en-IN")}
          description="Current stock units"
          type="purple"
        />

        <MetricCard
          icon={<FiUsers />}
          title="Customers"
          value={number(
            getValue(
              customers.total,
              0
            )
          ).toLocaleString("en-IN")}
          description="Customers in your business"
          type="pink"
        />
      </div>

      {/* ======================================================
          SALES INTELLIGENCE
      ====================================================== */}

      <SectionHeader
        icon={<FiBarChart2 />}
        title="Sales Intelligence"
        description="Understand what is driving your revenue"
      />

      <div style={styles.twoColumn}>
        <div style={styles.largeCard}>
          <CardTitle
            icon={<FiTrendingUp />}
            title="Sales Performance"
          />

          <div style={styles.insightList}>
            <InsightRow
              label="Today Sales"
              value={money(
                sales.today?.revenue
              )}
            />

            <InsightRow
              label="Monthly Sales"
              value={money(
                sales.current_month?.revenue
              )}
            />

            <InsightRow
              label="Total Sales"
              value={money(
                sales.current_month?.revenue
              )}
            />

            <InsightRow
              label="Growth"
              value={percentage(
                sales.growth?.revenue_percent
              )}
            />
          </div>
        </div>

        <div style={styles.largeCard}>
          <CardTitle
            icon={<FiTarget />}
            title="AI Sales Insight"
          />

          <div style={styles.aiInsight}>
            <div style={styles.aiInsightIcon}>
              <FiZap size={22} />
            </div>

            <div>
              <div style={styles.aiLabel}>
                AI RECOMMENDATION
              </div>

              <div style={styles.aiText}>
                {salesStrategy.summary ||
                  salesStrategy.recommendation ||
                  salesStrategy.insight ||
                  executiveSummary.message ||
                  data.salesInsight ||
                  "The AI engine is analyzing your sales performance and will recommend the highest-impact actions."}
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* ======================================================
          INVENTORY INTELLIGENCE
      ====================================================== */}

      <SectionHeader
        icon={<FiPackage />}
        title="Inventory Intelligence"
        description="Know what to buy, what to reduce and what may become dead stock"
      />

      <div style={styles.cardGrid}>
        <MetricCard
          icon={<FiAlertTriangle />}
          title="Low Stock"
          value={number(
            inventory.low_stock_count
          )}
          description="Products needing attention"
          type="red"
        />

        <MetricCard
          icon={<FiShoppingCart />}
          title="Reorder"
          value={number(
            inventory.low_stock_count
          )}
          description="Products AI recommends buying"
          type="orange"
        />

        <MetricCard
          icon={<FiPackage />}
          title="Dead Stock"
          value={number(
            inventory.dead_stock_count
          )}
          description="Products with weak movement"
          type="gray"
        />

        <MetricCard
          icon={<FiTrendingDown />}
          title="Overstock"
          value={number(
            Array.isArray(inventory.overstocked_products)
              ? inventory.overstocked_products.length
              : 0
          )}
          description="Products with excess stock"
          type="purple"
        />
      </div>

      {/* ======================================================
          INVENTORY AI RECOMMENDATION
      ====================================================== */}

      <div style={styles.largeCard}>
        <CardTitle
          icon={<FiZap />}
          title="Inventory Action Plan"
        />

        <div style={styles.actionGrid}>
          <ActionBox
            title="Buy More"
            text={
              inventoryStrategy.recommendation ||
              inventoryStrategy.buy_more ||
              inventory.buyMore ||
              inventory.reorderRecommendation ||
              "Prioritize products with low stock and strong recent demand."
            }
            icon={<FiShoppingCart />}
            type="green"
          />

          <ActionBox
            title="Reduce Stock"
            text={
              inventoryStrategy.reduce_stock ||
              inventoryStrategy.overstockRecommendation ||
              inventory.reduce ||
              inventory.overstockRecommendation ||
              "Reduce excess inventory and avoid tying up business cash."
            }
            icon={<FiTrendingDown />}
            type="orange"
          />

          <ActionBox
            title="Promote Dead Stock"
            text={
              inventoryStrategy.dead_stock ||
              inventoryStrategy.deadStockRecommendation ||
              "Create offers or bundles for slow-moving products."
            }
            icon={<FiTarget />}
            type="purple"
          />
        </div>
      </div>

      {/* ======================================================
          CUSTOMER INTELLIGENCE
      ====================================================== */}

      <SectionHeader
        icon={<FiUsers />}
        title="Customer Intelligence"
        description="Understand customer behavior and find opportunities"
      />

      <div style={styles.twoColumn}>
        <div style={styles.largeCard}>
          <CardTitle
            icon={<FiUsers />}
            title="Customer Analysis"
          />

          <div style={styles.insightList}>
            <InsightRow
              label="Total Customers"
              value={number(
                customers.total
              )}
            />

            <InsightRow
              label="Repeat Customers"
              value={number(
                customers.total_orders
              )}
            />

            <InsightRow
              label="Inactive Customers"
              value={number(
                customers.inactive_60_days
              )}
            />

            <InsightRow
              label="Retention"
              value={percentage(
                0
              )}
            />
          </div>
        </div>

        <div style={styles.largeCard}>
          <CardTitle
            icon={<FiTarget />}
            title="Customer Opportunity"
          />

          <div style={styles.aiInsight}>
            <div style={styles.aiInsightIcon}>
              <FiUsers size={22} />
            </div>

            <div>
              <div style={styles.aiLabel}>
                AI CUSTOMER STRATEGY
              </div>

              <div style={styles.aiText}>
                {customerStrategy.recommendation ||
                  customerStrategy.summary ||
                  customerStrategy.insight ||
                  customers.insight ||
                  customers.recommendation ||
                  data.customerInsight ||
                  "Target repeat customers with personalized offers and bring inactive customers back with relevant promotions."}
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* ======================================================
          PROFIT INTELLIGENCE
      ====================================================== */}

      <SectionHeader
        icon={<FiDollarSign />}
        title="Profit Intelligence"
        description="Find where your business is making and losing money"
      />

      <div style={styles.cardGrid}>
        <MetricCard
          icon={<FiDollarSign />}
          title="Estimated Profit"
          value={money(
            inventory.potential_profit
          )}
          description="Estimated business profit"
          type="green"
        />

        <MetricCard
          icon={<FiBarChart2 />}
          title="Profit Margin"
          value={percentage(
            inventory.potential_margin_percent
          )}
          description="Estimated margin"
          type="blue"
        />

        <MetricCard
          icon={<FiTrendingUp />}
          title="High Profit Products"
          value={number(
            Array.isArray(products.high_margin)
              ? products.high_margin.length
              : 0
          )}
          description="Products generating strong margin"
          type="purple"
        />

        <MetricCard
          icon={<FiTrendingDown />}
          title="Low Margin Products"
          value={number(
            Array.isArray(products.low_margin)
              ? products.low_margin.length
              : 0
          )}
          description="Products needing review"
          type="red"
        />
      </div>

      {/* ======================================================
          AI OPPORTUNITIES
      ====================================================== */}

      <SectionHeader
        icon={<FiZap />}
        title="AI Business Opportunities"
        description="Actions that may improve revenue, profit and efficiency"
      />

      <div style={styles.opportunityGrid}>
        {Array.isArray(opportunities) &&
        opportunities.length > 0 ? (
          opportunities.map((item, index) => (
            <OpportunityCard
              key={index}
              item={item}
              index={index}
            />
          ))
        ) : (
          <>
            <OpportunityCard
              index={1}
              item={{
                title: "Increase Sales",
                description:
                  "Identify your best-selling products and create focused promotions around them.",
              }}
            />

            <OpportunityCard
              index={2}
              item={{
                title: "Improve Inventory",
                description:
                  "Reduce slow-moving stock and reorder products with strong demand.",
              }}
            />

            <OpportunityCard
              index={3}
              item={{
                title: "Grow Customers",
                description:
                  "Target existing customers with repeat-purchase offers.",
              }}
            />
          </>
        )}
      </div>

      {/* ======================================================
          BUSINESS RISKS
      ====================================================== */}

      <SectionHeader
        icon={<FiShield />}
        title="Business Risks"
        description="Potential problems that need attention"
      />

      <div style={styles.riskGrid}>
        {Array.isArray(risks) &&
        risks.length > 0 ? (
          risks.map((item, index) => (
            <RiskCard
              key={index}
              item={item}
            />
          ))
        ) : (
          <>
            <RiskCard
              item={{
                title: "Inventory Risk",
                description:
                  "Monitor low-stock and slow-moving products regularly.",
              }}
            />

            <RiskCard
              item={{
                title: "Sales Risk",
                description:
                  "Watch for declining sales and weak-performing periods.",
              }}
            />

            <RiskCard
              item={{
                title: "Customer Risk",
                description:
                  "Inactive customers may reduce future repeat revenue.",
              }}
            />
          </>
        )}
      </div>

      {/* ======================================================
          GROWTH STRATEGY
      ====================================================== */}

      <SectionHeader
        icon={<FiTarget />}
        title="AI Growth Strategy"
        description="A practical plan for improving the business"
      />

      <div style={styles.strategyGrid}>
        <StrategyCard
          icon={<FiZap />}
          title="Today"
          text={
            salesStrategy.today ||
            inventoryStrategy.today ||
            strategy.today ||
            data.todayStrategy ||
            "Review today's sales, urgent stock issues and the highest-priority opportunities."
          }
        />

        <StrategyCard
          icon={<FiCalendar />}
          title="This Week"
          text={
            salesStrategy.this_week ||
            inventoryStrategy.this_week ||
            customerStrategy.this_week ||
            strategy.week ||
            strategy.thisWeek ||
            data.weekStrategy ||
            "Focus on best-selling products, customer retention and inventory optimization."
          }
        />

        <StrategyCard
          icon={<FiBarChart2 />}
          title="This Month"
          text={
            productStrategy.this_month ||
            customerStrategy.this_month ||
            strategy.month ||
            strategy.thisMonth ||
            data.monthStrategy ||
            "Improve margins, increase repeat purchases and reduce dead inventory."
          }
        />

        <StrategyCard
          icon={<FiTrendingUp />}
          title="Next 3 Months"
          text={
            salesStrategy.next_3_months ||
            inventoryStrategy.next_3_months ||
            strategy.threeMonths ||
            strategy.nextThreeMonths ||
            data.threeMonthStrategy ||
            "Build a consistent growth plan based on sales, customer and inventory trends."
          }
        />
      </div>

      {/* ======================================================
          ACTION PLAN
      ====================================================== */}

      <SectionHeader
        icon={<FiCheckCircle />}
        title="Recommended Action Plan"
        description="Prioritized actions for the business owner"
      />

      <div style={styles.actionPlan}>
        {Array.isArray(actions) &&
        actions.length > 0 ? (
          actions.map((item, index) => (
            <div
              key={index}
              style={styles.actionPlanRow}
            >
              <div style={styles.actionNumber}>
                {index + 1}
              </div>

              <div style={{ flex: 1 }}>
                <div style={styles.actionTitle}>
                  {typeof item === "string"
                    ? item
                    : item.title ||
                      item.action ||
                      "Recommended Action"}
                </div>

                {typeof item !== "string" &&
                  item.description && (
                    <div style={styles.actionDescription}>
                      {item.description}
                    </div>
                  )}
              </div>

              <FiCheckCircle
                size={20}
                style={{ color: "#16a34a" }}
              />
            </div>
          ))
        ) : (
          <>
            <ActionPlanRow
              number="1"
              title="Review low-stock products"
              description="Prevent missed sales by keeping important products available."
            />

            <ActionPlanRow
              number="2"
              title="Promote slow-moving products"
              description="Use offers and bundles to convert dead stock into revenue."
            />

            <ActionPlanRow
              number="3"
              title="Target repeat customers"
              description="Increase customer lifetime value with repeat-purchase campaigns."
            />

            <ActionPlanRow
              number="4"
              title="Review product margins"
              description="Identify products where pricing or purchasing costs need improvement."
            />
          </>
        )}
      </div>

      {/* ======================================================
          AI STATUS
      ====================================================== */}

      <div style={styles.footerAI}>
        <div style={styles.footerIcon}>
          <FiZap size={25} />
        </div>

        <div>
          <div style={styles.footerTitle}>
            AI Business Engine
          </div>

          <div style={styles.footerText}>
            Your business data is being converted into practical decisions, priorities and strategies.
          </div>
        </div>

        <div style={styles.activeBadge}>
          <span style={styles.activeDot}></span>
          Active
        </div>
      </div>

      {/* ======================================================
          CSS
      ====================================================== */}

      <style>
        {`
          @keyframes aiSpin {
            from {
              transform: rotate(0deg);
            }
            to {
              transform: rotate(360deg);
            }
          }

          @keyframes aiPulse {
            0%, 100% {
              opacity: 1;
            }
            50% {
              opacity: .55;
            }
          }

          * {
            box-sizing: border-box;
          }

          @media (max-width: 900px) {
            .ai-two-column {
              grid-template-columns: 1fr !important;
            }
          }

          @media (max-width: 700px) {
            .executiveGrid {
              grid-template-columns: 1fr !important;
            }
          }
        `}
      </style>
    </div>
  );
}

// ============================================================
// SECTION HEADER
// ============================================================

function SectionHeader({
  icon,
  title,
  description,
}) {
  return (
    <div style={styles.sectionHeader}>
      <div style={styles.sectionIcon}>
        {icon}
      </div>

      <div>
        <h2 style={styles.sectionTitle}>
          {title}
        </h2>

        <p style={styles.sectionDescription}>
          {description}
        </p>
      </div>
    </div>
  );
}

// ============================================================
// METRIC CARD
// ============================================================

function MetricCard({
  icon,
  title,
  value,
  description,
  type,
}) {
  const theme = getTheme(type);

  return (
    <div
      style={{
        ...styles.metricCard,
        borderTop: `3px solid ${theme.main}`,
      }}
    >
      <div
        style={{
          ...styles.metricIcon,
          background: theme.background,
          color: theme.main,
        }}
      >
        {icon}
      </div>

      <div style={styles.metricTitle}>
        {title}
      </div>

      <div style={styles.metricValue}>
        {value}
      </div>

      <div style={styles.metricDescription}>
        {description}
      </div>
    </div>
  );
}

// ============================================================
// CARD TITLE
// ============================================================

function CardTitle({ icon, title }) {
  return (
    <div style={styles.cardTitle}>
      <div style={styles.cardTitleIcon}>
        {icon}
      </div>

      <h3 style={styles.cardTitleText}>
        {title}
      </h3>
    </div>
  );
}

// ============================================================
// INSIGHT ROW
// ============================================================

function InsightRow({ label, value }) {
  return (
    <div style={styles.insightRow}>
      <span style={styles.insightLabel}>
        {label}
      </span>

      <strong style={styles.insightValue}>
        {value}
      </strong>
    </div>
  );
}

// ============================================================
// AI ACTION BOX
// ============================================================

function ActionBox({
  title,
  text,
  icon,
  type,
}) {
  const theme = getTheme(type);

  return (
    <div
      style={{
        ...styles.actionBox,
        background: theme.background,
        borderColor: `${theme.main}30`,
      }}
    >
      <div
        style={{
          ...styles.actionIcon,
          color: theme.main,
        }}
      >
        {icon}
      </div>

      <div>
        <div style={styles.actionBoxTitle}>
          {title}
        </div>

        <div style={styles.actionBoxText}>
          {text}
        </div>
      </div>
    </div>
  );
}

// ============================================================
// OPPORTUNITY CARD
// ============================================================

function OpportunityCard({
  item,
  index,
}) {
  const title =
    typeof item === "string"
      ? item
      : item?.title ||
        item?.name ||
        `Opportunity ${index}`;

  const description =
    typeof item === "string"
      ? ""
      : item?.description ||
        item?.reason ||
        item?.recommendation ||
        "";

  return (
    <div style={styles.opportunityCard}>
      <div style={styles.opportunityNumber}>
        {index}
      </div>

      <div style={{ flex: 1 }}>
        <div style={styles.opportunityTitle}>
          {title}
        </div>

        <div style={styles.opportunityDescription}>
          {description ||
            "AI identified this as a potential business improvement opportunity."}
        </div>
      </div>

      <FiZap
        size={21}
        style={{
          color: "#7c3aed",
          flexShrink: 0,
        }}
      />
    </div>
  );
}

// ============================================================
// RISK CARD
// ============================================================

function RiskCard({ item }) {
  const title =
    typeof item === "string"
      ? item
      : item?.title ||
        item?.name ||
        "Business Risk";

  const description =
    typeof item === "string"
      ? ""
      : item?.description ||
        item?.reason ||
        "";

  return (
    <div style={styles.riskCard}>
      <div style={styles.riskIcon}>
        <FiAlertTriangle size={21} />
      </div>

      <div>
        <div style={styles.riskTitle}>
          {title}
        </div>

        <div style={styles.riskDescription}>
          {description ||
            "AI recommends monitoring this area carefully."}
        </div>
      </div>
    </div>
  );
}

// ============================================================
// STRATEGY CARD
// ============================================================

function StrategyCard({
  icon,
  title,
  text,
}) {
  return (
    <div style={styles.strategyCard}>
      <div style={styles.strategyIcon}>
        {icon}
      </div>

      <div style={styles.strategyTitle}>
        {title}
      </div>

      <div style={styles.strategyText}>
        {text}
      </div>
    </div>
  );
}

// ============================================================
// ACTION PLAN ROW
// ============================================================

function ActionPlanRow({
  number,
  title,
  description,
}) {
  return (
    <div style={styles.actionPlanRow}>
      <div style={styles.actionNumber}>
        {number}
      </div>

      <div style={{ flex: 1 }}>
        <div style={styles.actionTitle}>
          {title}
        </div>

        <div style={styles.actionDescription}>
          {description}
        </div>
      </div>

      <FiCheckCircle
        size={20}
        style={{ color: "#16a34a" }}
      />
    </div>
  );
}

// ============================================================
// COLOR THEMES
// ============================================================

function getTheme(type) {
  const themes = {
    green: {
      main: "#16a34a",
      background: "#f0fdf4",
    },

    blue: {
      main: "#2563eb",
      background: "#eff6ff",
    },

    purple: {
      main: "#7c3aed",
      background: "#f5f3ff",
    },

    pink: {
      main: "#db2777",
      background: "#fdf2f8",
    },

    red: {
      main: "#dc2626",
      background: "#fef2f2",
    },

    orange: {
      main: "#ea580c",
      background: "#fff7ed",
    },

    gray: {
      main: "#64748b",
      background: "#f8fafc",
    },
  };

  return themes[type] || themes.blue;
}

// ============================================================
// STYLES
// ============================================================

const styles = {
  page: {
    minHeight: "100vh",
    background:
      "linear-gradient(135deg, #f5f7fb 0%, #e8edf5 100%)",
    padding: "30px",
    color: "#1a2332",
  },

  header: {
    maxWidth: "1400px",
    margin: "0 auto 25px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "20px",
    flexWrap: "wrap",
  },

  headerLeft: {
    display: "flex",
    alignItems: "center",
    gap: "18px",
  },

  backButton: {
    display: "flex",
    alignItems: "center",
    gap: "7px",
    padding: "10px 15px",
    background: "#fff",
    color: "#475569",
    border: "1px solid #e2e8f0",
    borderRadius: "10px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "600",
  },

  titleRow: {
    display: "flex",
    alignItems: "center",
    gap: "13px",
  },

  aiIcon: {
    width: "52px",
    height: "52px",
    borderRadius: "15px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background:
      "linear-gradient(135deg, #7c3aed, #2563eb)",
    color: "#fff",
    boxShadow:
      "0 8px 20px rgba(99,102,241,.25)",
  },

  title: {
    margin: 0,
    fontSize: "30px",
    fontWeight: "800",
    letterSpacing: "-0.5px",
  },

  subtitle: {
    margin: "5px 0 0",
    color: "#64748b",
    fontSize: "14px",
  },

  analyzeButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "9px",
    padding: "13px 20px",
    border: "none",
    borderRadius: "11px",
    background:
      "linear-gradient(135deg, #7c3aed, #2563eb)",
    color: "#fff",
    cursor: "pointer",
    fontWeight: "700",
    fontSize: "14px",
    boxShadow:
      "0 7px 18px rgba(99,102,241,.25)",
  },

  businessBanner: {
    maxWidth: "1400px",
    margin: "0 auto 30px",
    padding: "28px 32px",
    borderRadius: "20px",
    background:
      "linear-gradient(135deg, #111827 0%, #1e293b 50%, #312e81 100%)",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "20px",
    flexWrap: "wrap",
    boxShadow:
      "0 12px 35px rgba(15,23,42,.16)",
  },

  bannerSmall: {
    fontSize: "11px",
    letterSpacing: "1.5px",
    opacity: 0.65,
    fontWeight: "700",
    marginBottom: "7px",
  },

  bannerName: {
    fontSize: "25px",
    fontWeight: "800",
  },

  bannerDescription: {
    marginTop: "6px",
    fontSize: "13px",
    opacity: 0.7,
    maxWidth: "650px",
  },

  bannerAI: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "7px",
    padding: "18px 24px",
    borderRadius: "15px",
    background: "rgba(255,255,255,.08)",
    border: "1px solid rgba(255,255,255,.12)",
    fontSize: "11px",
    fontWeight: "800",
    letterSpacing: "1px",
  },

  sectionHeader: {
    maxWidth: "1400px",
    margin: "38px auto 17px",
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },

  sectionIcon: {
    width: "40px",
    height: "40px",
    borderRadius: "11px",
    background: "#fff",
    color: "#7c3aed",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 3px 10px rgba(0,0,0,.05)",
  },

  sectionTitle: {
    margin: 0,
    fontSize: "21px",
    fontWeight: "750",
  },

  sectionDescription: {
    margin: "3px 0 0",
    color: "#64748b",
    fontSize: "13px",
  },

  cardGrid: {
    maxWidth: "1400px",
    margin: "0 auto",
    display: "grid",
    gridTemplateColumns:
      "repeat(auto-fit, minmax(230px, 1fr))",
    gap: "18px",
  },

  metricCard: {
    background: "#fff",
    borderRadius: "16px",
    padding: "21px",
    boxShadow: "0 4px 14px rgba(0,0,0,.055)",
    borderLeft: "1px solid #edf1f6",
    borderRight: "1px solid #edf1f6",
    borderBottom: "1px solid #edf1f6",
  },

  metricIcon: {
    width: "43px",
    height: "43px",
    borderRadius: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "15px",
  },

  metricTitle: {
    color: "#64748b",
    fontSize: "13px",
    fontWeight: "600",
  },

  metricValue: {
    marginTop: "5px",
    fontSize: "27px",
    fontWeight: "800",
    color: "#172033",
  },

  metricDescription: {
    marginTop: "5px",
    color: "#94a3b8",
    fontSize: "12px",
  },

  twoColumn: {
    maxWidth: "1400px",
    margin: "0 auto",
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "18px",
  },

  largeCard: {
    maxWidth: "1400px",
    margin: "0 auto 18px",
    background: "#fff",
    borderRadius: "16px",
    padding: "24px",
    boxShadow: "0 4px 14px rgba(0,0,0,.055)",
    border: "1px solid rgba(0,0,0,.035)",
  },

  cardTitle: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "20px",
  },

  cardTitleIcon: {
    color: "#7c3aed",
    width: "35px",
    height: "35px",
    borderRadius: "9px",
    background: "#f5f3ff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },

  cardTitleText: {
    margin: 0,
    fontSize: "17px",
    fontWeight: "700",
  },

  insightList: {
    display: "flex",
    flexDirection: "column",
  },

  insightRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "14px 0",
    borderBottom: "1px solid #eef2f7",
  },

  insightLabel: {
    color: "#64748b",
    fontSize: "14px",
  },

  insightValue: {
    color: "#172033",
    fontSize: "15px",
  },

  aiInsight: {
    display: "flex",
    gap: "14px",
    padding: "18px",
    borderRadius: "14px",
    background:
      "linear-gradient(135deg, #f5f3ff, #eff6ff)",
    border: "1px solid #e5e7eb",
  },

  aiInsightIcon: {
    width: "42px",
    height: "42px",
    flexShrink: 0,
    borderRadius: "11px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background:
      "linear-gradient(135deg, #7c3aed, #2563eb)",
    color: "#fff",
  },

  aiLabel: {
    fontSize: "10px",
    fontWeight: "800",
    letterSpacing: "1px",
    color: "#7c3aed",
    marginBottom: "5px",
  },

  aiText: {
    color: "#334155",
    lineHeight: "1.65",
    fontSize: "14px",
  },

  actionGrid: {
    display: "grid",
    gridTemplateColumns:
      "repeat(auto-fit, minmax(250px, 1fr))",
    gap: "14px",
  },

  actionBox: {
    display: "flex",
    gap: "13px",
    padding: "17px",
    borderRadius: "13px",
    border: "1px solid",
  },

  actionIcon: {
    width: "38px",
    height: "38px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },

  actionBoxTitle: {
    fontWeight: "700",
    fontSize: "14px",
    marginBottom: "5px",
  },

  actionBoxText: {
    color: "#64748b",
    fontSize: "12px",
    lineHeight: "1.55",
  },

  opportunityGrid: {
    maxWidth: "1400px",
    margin: "0 auto",
    display: "grid",
    gridTemplateColumns:
      "repeat(auto-fit, minmax(300px, 1fr))",
    gap: "16px",
  },

  opportunityCard: {
    display: "flex",
    alignItems: "flex-start",
    gap: "13px",
    background: "#fff",
    borderRadius: "15px",
    padding: "19px",
    boxShadow: "0 4px 14px rgba(0,0,0,.055)",
    border: "1px solid #eeeafc",
  },

  opportunityNumber: {
    width: "35px",
    height: "35px",
    flexShrink: 0,
    borderRadius: "10px",
    background: "#f5f3ff",
    color: "#7c3aed",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "800",
    fontSize: "13px",
  },

  opportunityTitle: {
    fontWeight: "750",
    fontSize: "15px",
    marginBottom: "5px",
  },

  opportunityDescription: {
    color: "#64748b",
    fontSize: "12px",
    lineHeight: "1.55",
  },

  riskGrid: {
    maxWidth: "1400px",
    margin: "0 auto",
    display: "grid",
    gridTemplateColumns:
      "repeat(auto-fit, minmax(300px, 1fr))",
    gap: "16px",
  },

  riskCard: {
    display: "flex",
    alignItems: "flex-start",
    gap: "13px",
    background: "#fff",
    borderRadius: "15px",
    padding: "19px",
    border: "1px solid #fee2e2",
    boxShadow: "0 4px 14px rgba(0,0,0,.04)",
  },

  riskIcon: {
    width: "40px",
    height: "40px",
    flexShrink: 0,
    borderRadius: "11px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#dc2626",
    background: "#fef2f2",
  },

  riskTitle: {
    fontWeight: "750",
    fontSize: "15px",
    marginBottom: "5px",
  },

  riskDescription: {
    color: "#64748b",
    fontSize: "12px",
    lineHeight: "1.55",
  },

  strategyGrid: {
    maxWidth: "1400px",
    margin: "0 auto",
    display: "grid",
    gridTemplateColumns:
      "repeat(auto-fit, minmax(260px, 1fr))",
    gap: "16px",
  },

  strategyCard: {
    background: "#fff",
    padding: "22px",
    borderRadius: "16px",
    boxShadow: "0 4px 14px rgba(0,0,0,.055)",
    borderTop: "3px solid #7c3aed",
  },

  strategyIcon: {
    width: "40px",
    height: "40px",
    borderRadius: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#7c3aed",
    background: "#f5f3ff",
    marginBottom: "14px",
  },

  strategyTitle: {
    fontSize: "16px",
    fontWeight: "800",
    marginBottom: "8px",
  },

  strategyText: {
    color: "#64748b",
    fontSize: "13px",
    lineHeight: "1.65",
  },

  actionPlan: {
    maxWidth: "1400px",
    margin: "0 auto",
    background: "#fff",
    borderRadius: "16px",
    padding: "8px 22px",
    boxShadow: "0 4px 14px rgba(0,0,0,.055)",
  },

  actionPlanRow: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    padding: "17px 5px",
    borderBottom: "1px solid #eef2f7",
  },

  actionNumber: {
    width: "34px",
    height: "34px",
    flexShrink: 0,
    borderRadius: "50%",
    background: "#eff6ff",
    color: "#2563eb",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "13px",
    fontWeight: "800",
  },

  actionTitle: {
    fontSize: "14px",
    fontWeight: "700",
    color: "#1e293b",
  },

  actionDescription: {
    marginTop: "4px",
    color: "#64748b",
    fontSize: "12px",
    lineHeight: "1.5",
  },

  footerAI: {
    maxWidth: "1400px",
    margin: "35px auto 0",
    padding: "22px 25px",
    borderRadius: "16px",
    background:
      "linear-gradient(135deg, #111827, #312e81)",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    gap: "14px",
  },

  footerIcon: {
    width: "45px",
    height: "45px",
    borderRadius: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "rgba(255,255,255,.1)",
  },

  footerTitle: {
    fontSize: "15px",
    fontWeight: "800",
  },

  footerText: {
    marginTop: "4px",
    fontSize: "12px",
    opacity: 0.7,
  },

  activeBadge: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: "7px",
    padding: "7px 12px",
    borderRadius: "20px",
    background: "rgba(34,197,94,.12)",
    color: "#86efac",
    fontSize: "12px",
    fontWeight: "700",
  },

  activeDot: {
    width: "7px",
    height: "7px",
    borderRadius: "50%",
    background: "#22c55e",
    animation: "aiPulse 1.5s infinite",
  },

  executiveGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 220px",
    gap: "18px",
    alignItems: "stretch",
  },

  executiveSummaryBox: {
    padding: "20px",
    borderRadius: "14px",
    background: "linear-gradient(135deg, #f5f3ff, #eff6ff)",
    border: "1px solid #e5e7eb",
  },

  executiveText: {
    marginTop: "7px",
    color: "#334155",
    fontSize: "14px",
    lineHeight: "1.7",
  },

  healthBox: {
    padding: "20px",
    borderRadius: "14px",
    background: "#111827",
    color: "#fff",
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },

  healthLabel: {
    fontSize: "10px",
    letterSpacing: "1px",
    fontWeight: "800",
    opacity: 0.7,
  },

  healthScore: {
    marginTop: "6px",
    fontSize: "38px",
    fontWeight: "900",
  },

  healthStatus: {
    marginTop: "2px",
    fontSize: "13px",
    fontWeight: "700",
    opacity: 0.8,
  },

  errorBox: {
    maxWidth: "1400px",
    margin: "0 auto 25px",
    padding: "16px 18px",
    borderRadius: "13px",
    background: "#fef2f2",
    color: "#b91c1c",
    border: "1px solid #fecaca",
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },

  errorText: {
    marginTop: "3px",
    fontSize: "12px",
  },

  retryButton: {
    marginLeft: "auto",
    border: "none",
    background: "#dc2626",
    color: "#fff",
    padding: "8px 14px",
    borderRadius: "8px",
    cursor: "pointer",
    fontWeight: "600",
  },

  loadingBox: {
    minHeight: "80vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },

  aiLoadingIcon: {
    width: "70px",
    height: "70px",
    borderRadius: "20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#fff",
    background:
      "linear-gradient(135deg, #7c3aed, #2563eb)",
    boxShadow:
      "0 12px 30px rgba(99,102,241,.25)",
  },

  loadingTitle: {
    margin: "18px 0 5px",
    fontSize: "23px",
  },

  loadingText: {
    color: "#64748b",
    fontSize: "14px",
  },

  spinner: {
    width: "28px",
    height: "28px",
    marginTop: "15px",
    borderRadius: "50%",
    border: "3px solid #e2e8f0",
    borderTop: "3px solid #7c3aed",
    animation: "aiSpin 1s linear infinite",
  },
};